type TabId = 'Adjust' | 'Annotate' | 'Filters' | 'Finetune' | 'Resize' | 'Watermark'

const translations = {
  name: '名称',
  save: '保存',
  saveAs: '另存为',
  back: '返回',
  loading: '正在加载...',
  resetOperations: '重置并删除全部编辑',
  changesLoseWarningHint: '重置后将丢失全部修改，是否继续？',
  discardChangesWarningHint: '关闭后未保存的修改将丢失。',
  cancel: '取消',
  apply: '应用',
  warning: '提示',
  confirm: '确认',
  discardChanges: '放弃修改',
  undoTitle: '撤销上一步',
  redoTitle: '重做上一步',
  showImageTitle: '查看原图',
  zoomInTitle: '放大',
  fitTitle: '适应画布',
  zoomOutTitle: '缩小',
  toggleZoomMenuTitle: '切换缩放菜单',
  adjustTab: '调整',
  finetuneTab: '微调',
  filtersTab: '滤镜',
  watermarkTab: '水印',
  annotateTabLabel: '标注',
  resize: '调整尺寸',
  resizeTab: '尺寸',
  imageName: '图片名称',
  invalidImageError: '图片无效。',
  uploadImageError: '图片上传失败。',
  areNotImages: '不是图片',
  isNotImage: '不是图片',
  toBeUploaded: '等待上传',
  cropTool: '裁剪',
  original: '原始比例',
  custom: '自定义',
  square: '正方形',
  landscape: '横向',
  portrait: '纵向',
  ellipse: '椭圆',
  classicTv: '经典电视',
  cinemascope: '宽银幕',
  arrowTool: '箭头',
  blurTool: '模糊',
  brightnessTool: '亮度',
  contrastTool: '对比度',
  ellipseTool: '椭圆',
  unFlipX: '取消水平翻转',
  flipX: '水平翻转',
  unFlipY: '取消垂直翻转',
  flipY: '垂直翻转',
  hsvTool: '色相与饱和度',
  hue: '色相',
  brightness: '亮度',
  saturation: '饱和度',
  value: '明度',
  imageTool: '图片',
  importing: '正在导入...',
  addImage: '添加图片',
  uploadImage: '上传图片',
  fromGallery: '从图库选择',
  lineTool: '直线',
  penTool: '画笔',
  polygonTool: '多边形',
  sides: '边数',
  rectangleTool: '矩形',
  cornerRadius: '圆角',
  resizeWidthTitle: '宽度（像素）',
  resizeHeightTitle: '高度（像素）',
  toggleRatioLockTitle: '锁定宽高比例',
  resetSize: '恢复原始尺寸',
  rotateTool: '旋转',
  textTool: '文字',
  textSpacings: '文字间距',
  textAlignment: '文字对齐',
  fontFamily: '字体',
  size: '大小',
  letterSpacing: '字间距',
  lineHeight: '行高',
  warmthTool: '色温',
  addWatermark: '添加水印',
  addTextWatermark: '添加文字水印',
  addWatermarkTitle: '选择水印类型',
  uploadWatermark: '上传水印图片',
  addWatermarkAsText: '添加文字水印',
  padding: '边距',
  paddings: '边距',
  shadow: '阴影',
  horizontal: '水平',
  vertical: '垂直',
  blur: '模糊',
  opacity: '不透明度',
  transparency: '透明度',
  position: '位置',
  stroke: '描边',
  saveAsModalTitle: '保存图片',
  extension: '扩展名',
  format: '格式',
  nameIsRequired: '请输入图片名称。',
  quality: '质量',
  imageDimensionsHoverTitle: '保存尺寸（宽 × 高）',
  cropSizeLowerThanResizedWarning: '裁剪区域小于设置的输出尺寸，可能降低图片质量。',
  actualSize: '实际大小（100%）',
  fitSize: '适应窗口',
  addImageTitle: '选择要添加的图片',
  mutualizedFailedToLoadImg: '图片加载失败。',
  tabsMenu: '工具菜单',
  download: '下载',
  width: '宽度',
  height: '高度',
  cropItemNoEffect: '该裁剪比例暂无预览',
  px: '像素',
  invalidTextContent: '文字内容无效',
  baselineShift: '基线偏移',
  aiTab: '智能工具',
  objectRemovalTool: '移除物体',
  objectRemovalBrushSize: '画笔大小（像素）',
  objectRemovalApplyButton: '应用',
  objectRemovalBrushMode: '画笔模式',
  objectRemovalBrushCircleType: '圆形画笔',
  objectRemovalBrushSquareType: '方形画笔',
  objectRemovalApplyingText: '正在移除选中区域',
  objectRemovalMarkModeTooltip: '标记模式',
  objectRemovalUnMarkModeTooltip: '取消标记',
  objectRemovalCancelConfirmationTitle: '取消处理',
  objectRemovalCancelConfirmationHint: '确定取消处理',
  objectRemovalCancelConfirmationHintCompletion: '这张图片吗？',
  theKeyword: '当前',
}

export const filerobotConfig = {
  tabsIds: ['Adjust', 'Annotate', 'Filters', 'Finetune', 'Resize', 'Watermark'] as TabId[],
  defaultTabId: 'Adjust' as const,
  defaultToolId: 'Crop' as const,
  annotationsCommon: {
    fill: '#ec4899',
    stroke: '#ec4899',
    strokeWidth: 2,
  },
  Text: {
    text: '在此输入文字',
    fontFamily: 'Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
    fonts: [
      { label: '系统中文字体', value: 'Arial, "PingFang SC", "Microsoft YaHei", sans-serif' },
    ],
  },
  Watermark: {
    hideTextWatermark: false,
  },
  language: 'zh',
  translations,
  useBackendTranslations: false,
  defaultSavedImageName: '编辑图片',
  defaultSavedImageType: 'png' as const,
  defaultSavedImageQuality: 0.92,
  savingPixelRatio: 1,
  previewPixelRatio: 1,
  observePluginContainerSize: true,
  avoidChangesNotSavedAlertOnLeave: false,
  closeAfterSave: false,
}

export function getFilerobotTheme(dark: boolean) {
  if (!dark) {
    return {
      palette: {
        'accent-primary': '#ec4899',
        'accent-primary-hover': '#db2777',
        'accent-primary-active': '#be185d',
        'accent-stateless': '#ec4899',
        'bg-primary-active': '#fce7f3',
      },
    }
  }

  return {
    palette: {
      'txt-primary': '#f4f4f5',
      'txt-secondary': '#a1a1aa',
      'txt-secondary-invert': '#d4d4d8',
      'txt-placeholder': '#71717a',
      'accent-primary': '#ec4899',
      'accent-primary-hover': '#db2777',
      'accent-primary-active': '#be185d',
      'accent-primary-disabled': '#3f3f46',
      'accent-stateless': '#ec4899',
      'accent-stateless_0_4_opacity': 'rgba(236, 72, 153, 0.4)',
      accent_0_5_opacity: 'rgba(236, 72, 153, 0.08)',
      accent_1_2_opacity: 'rgba(236, 72, 153, 0.12)',
      accent_1_8_opacity: 'rgba(236, 72, 153, 0.18)',
      accent_2_8_opacity: 'rgba(236, 72, 153, 0.28)',
      accent_4_0_opacity: 'rgba(236, 72, 153, 0.4)',
      'bg-grey': '#09090b',
      'bg-stateless': '#18181b',
      'bg-active': '#27272a',
      'bg-base-light': '#27272a',
      'bg-base-medium': '#3f3f46',
      'bg-primary': '#18181b',
      'bg-primary-light': '#18181b',
      'bg-primary-hover': '#27272a',
      'bg-primary-active': '#3f3f46',
      'bg-primary-stateless': '#52525b',
      'bg-secondary': '#111113',
      'bg-hover': '#27272a',
      'bg-tooltip': '#27272a',
      'icon-primary': '#d4d4d8',
      'icons-primary-opacity-0-6': 'rgba(212, 212, 216, 0.6)',
      'icons-secondary': '#a1a1aa',
      'icons-placeholder': '#52525b',
      'icons-invert': '#18181b',
      'icons-muted': '#71717a',
      'icons-primary-hover': '#fafafa',
      'icons-secondary-hover': '#d4d4d8',
      'btn-primary-text': '#ffffff',
      'btn-secondary-text': '#f4f4f5',
      'link-primary': '#d4d4d8',
      'link-stateless': '#d4d4d8',
      'link-hover': '#ffffff',
      'link-active': '#ffffff',
      'link-pressed': '#ec4899',
      'borders-primary': '#3f3f46',
      'borders-primary-hover': '#71717a',
      'borders-secondary': '#27272a',
      'borders-strong': '#52525b',
      'borders-invert': '#71717a',
      'borders-button': '#52525b',
      'borders-item': '#27272a',
      'borders-base-light': '#3f3f46',
      'borders-base-medium': '#52525b',
      'active-secondary': '#27272a',
      'active-secondary-hover': '#3f3f46',
      'light-shadow': 'rgba(0, 0, 0, 0.3)',
      'medium-shadow': 'rgba(0, 0, 0, 0.4)',
      'large-shadow': 'rgba(0, 0, 0, 0.5)',
      'x-large-shadow': 'rgba(0, 0, 0, 0.6)',
    },
  }
}
